###
POST http://localhost:8080/java/api/v1.0/members:register
Content-Type: application/json

{
  "name": "qrtt1",
  "email": "qrtt1@purefunc.net"
}

###
GET http://localhost:8080/java/api/v1.0/members?email=qrtt1@purefunc.net
Content-Type: application/json

###
POST http://localhost:8080/kotlin/api/v1.0/members:register
Content-Type: application/json

{
  "name": "qrtt1",
  "email": "qrtt1@purefunc.net"
}

###
GET http://localhost:8080/kotlin/api/v1.0/members?email=qrtt1@purefunc.net
Content-Type: application/json